uc-cdis/fence

README.md

Add link to the swagger UI page in README.

fix(swagger-link): add link to swagger docs

---

.codacy.yml

Adds `.codacy.yml` configuration file. Don't count the tests directory in coverage reporting.

fix(coverage): ignore tests directory

---

.codacy.yml
fence/auth.py
fence/blueprints/user.py
fence/resources/user/__init__.py
fence/settings.py
setup.py
tests/conftest.py
tests/test_oauth2.py
tests/utils/__init__.py

- Fix call to `validate_request_jwt` to include `user_api` argument to specify the desired issuer (since fence needs to use its own hostname, not the `USER_API` config variable)
- Add regression tests

fix(auth): fix bug in `has_oauth`

---

bin/fence-create
fence/__init__.py
fence/settings.py
tests/conftest.py

- resolve #22 
- app_config expects a module and app_init passes a string, switch to not depend on the parameter to be a string and allow root_dir to be passed as a parameter

fix(deployment): fix settings import

---

fence/blueprints/data.py
fence/blueprints/login.py
fence/blueprints/storage_creds.py
fence/jwt/token.py
fence/resources/storage/cdis_jwt.py
fence/resources/user/user_session.py
openapi/swagger.yaml
setup.py
tests/test_cdis.py
tests/test_credentials.py
tests/utils/cdis.py

resolve #48 
- rename user's refresh_token to api_key, it introduces unecessary confusion to call user's token as refresh_token because people would think this is Oauth2/OIDC but it's not.
- use 'expires_in' for both user credentials and data endpoint for consistency with oauth
- restrict `/credentials/cdis/access_token` endpoint only accessable by user's API key whose `azp` == `sub`
- fix how expiration param is handled - convert to int and max to 30 days for api key and 1h for access_token
need to merge https://github.com/uc-cdis/cdis-python-utils/pull/23 first

chore(api_key): rename user refresh token to api_key

---

fence/jwt/blacklist.py
fence/models.py
fence/oidc/grants/authorization_code_grant.py
fence/oidc/grants/refresh_token_grant.py
tests/conftest.py
tests/rfc6749/conftest.py
tests/rfc6749/test_oauth2.py

Resolves #148.
Key points:
- [Override authlib method](https://github.com/uc-cdis/fence/compare/fix/client?expand=1#diff-fb722da188e9b9f3342328c53791e416R89) which failed immediately on non-confidential (i.e. public) clients.
- Add some very basic regression tests.

fix/client: allow public client to use refresh token grant

---

.travis.yml
bin/fence-create
fence/auth.py
fence/blueprints/storage_creds.py
fence/jwt/token.py
fence/oidc/jwt_generator.py
fence/resources/storage/cdis_jwt.py
fence/scripting/fence_create.py
fence/settings.py
requirements.txt
tests/conftest.py
tests/credentials/api_key/test_access.py
tests/credentials/api_key/test_api_key.py
tests/credentials/google/test_credentials.py
tests/oidc/core/token/test_token_response.py
tests/utils/__init__.py
tests/utils/api_key.py

- Script to manage expired google account keys
- refactoring in fence-create for style and Python3 compatibility
- ensure tokens have 'azp' (authorized party field) to determine the client we're talking to
- I think this got lost at some point during the oidc merging
- make storage cred endpoints use information from token 
- fix tests to send token in header so storage creds endpoint tests pass
Relies on some fixes in cirrus for service account id validation:
https://github.com/uc-cdis/cirrus/pull/8

feat(google): temporary key expiration handling

---

fence/jwt/keys.py
requirements.txt
setup.py
tests/rfc7517/test_jwks.py

`/.well-known/jwks` endpoint was returning `n` and `e` as base64url-encoded, not base64urlUInt-encoded. This changes `Keypair` to use `python-jose` for creating the required fields in the JWK response, which fixes the problem.

fix(jwk): use jose library to return JWKs

---

requirements.txt
tests/conftest.py
tests/jwt/conftest.py
tests/jwt/test_keys.py
tests/multi_tenant/conftest.py
tests/oidc/core/token/test_id_token.py
tests/scripting/conftest.py
tests/scripting/test_fence-create.py
tests/test_data.py
tests/test_settings.py

For uc-cdis/authutils#4.
Use the authutils text fixtures from uc-cdis/authutils#8 (instead of loading keys from files), so the `tests/resources/keys` files are no longer necessary for testing.
Depends on uc-cdis/authutils#16.

refactor(test-fixtures): add RSA key fixtures

---

openapi/swagger.yaml

- Add POST `/link/google`
- Add details to `/link/google`
- More restful interpretation of service account registration 
- `/google/service_accounts` and `/google/service_account/{id}`
- GET (list service accounts for user)
- POST (new service account)
- Then for specific service accounts: GET, PATCH (change dataset access), DELETE
P.S. I've been using https://editor.swagger.io/ to visualize

chore(docs): update swagger for google endpoints

---

bin/fence-create
fence/settings.py

Resolves #114.
Hard-code attempt to load `/var/www/local_settings.py` if the module was not found in the first attempts. This way the script in the kubernetes pod is always able to locate the settings (since the file is [mounted to that location by the deployment settings](https://github.com/uc-cdis/cloud-automation/blob/268526e20a6e4520c077de2c409154a10d1c7ec6/kube/services/fence/fence-deploy.yaml#L74)).

fix(local-settings): load from /var/www

---

Dockerfile
fence/blueprints/data.py
tests/conftest.py
tests/test_data.py
tests/test_settings.py

- don't try to resolve scheme that's not supported yet (eg: gs)
- if the bucket is configured to be '*' (without creds) in settings, return the http url 
- latest pip is broken in docker build, pin to 9
- remove deadcode (http conf)

fix(data): support public bucket

---

bin/fence-create
fence/jwt/token.py
fence/scripting/fence_create.py

- fix bug because `args` is not dictionary-like
- fix using base URL because flask app not available
- fix argument to be the same as before: for example `access_token`, not `access`

fix(token-create): bugfix for token-create

---

fence/__init__.py
fence/blueprints/login/__init__.py
tests/conftest.py
tests/credentials/google/test_credentials.py
tests/link/test_link.py

* Fix configuration to allow not having Google as an IDP for user login but still allow the linking endpoints to work
* Will now set up fence up as a client for Google if information is provided in `OPENID_CONNECT` configuration but will NOT create a login endpoint for Google unless it's in the `ENABLED_IDENTITY_PROVIDERS`
resolve #268

PXD-859 fix(google-oidc): allow google client with callback without supporting login through google

---

fence/auth.py
fence/resources/user/user_session.py
fence/user.py
tests/conftest.py
tests/session/test_session.py

Check for valid `access_token` when opening the session. Verify that the user identifier provided in the `access_token` matches the one in the current session.

PXD-1004 Fix/stale access token

---

fence/local_settings.example.py

"Fence Multi-Tenant OAuth" is not something end user can understand
The name should be the final idp's name, and our major/only use case for multi tenant fence is NIH Login. So the default name in the template should be that

chore(setting): fix fence login name

---

fence/local_settings.example.py
fence/resources/google/access_utils.py
tests/google/test_access_utils.py
tests/test_settings.py

* remove_white_listed_service_account_ids now removes service account ids listed in settings in addition to monitoring service account
* local_settings.py needs to be updated for this to take effect

White list service account ids

---

fence/sync/sync_users.py
tests/dbgap_sync/conftest.py
tests/dbgap_sync/test_user_sync.py

When syncing user permissions from the user.yaml file in fence, if a user's permissions get revoked (user is removed from user.yaml file), the user's access_privileges get removed from the access_privilege table, but their email, user_id and admin status do not get removed from the User table. This allows users to maintain admin access after they have been removed from the user.yaml file.
We wouldn't want to remove the user because that would be an interruptive experience for user who browses public dataset. So let's just clear up the admin access

PXD-1505 Fix/admin user

---

fence/scripting/fence_create.py
tests/scripting/test_fence-create.py

* link_external_bucket now takes DB string as argument
* updated test to use DB string argument

Fix Link External Database

---

fence/utils.py

http://flask.pocoo.org/docs/0.12/api/#flask.Request.cookies
cookies
A dict with the contents of all cookies transmitted with the request.
We were getting the *values* and setting new cookies with those as the *name*. Need to set cookies for the *names* stored in the dict's keys.

fix(cookies): set cookies to expire based on their name *not* value

---

.travis.yml

https://github.com/travis-ci/travis-ci/issues/7940
Google's library is adding a boto.cfg that travis tries to load and bad things happen (issues with finding google modules, imports fail). We don't need this boto configuration in our CI. Added workaround per the issue above

fix(travis): remove added boto cfg that travis incorrectly tries to load

---

fence/blueprints/login/fence_login.py

authutils has new authlib for this fence_client. the interface changed, can no longer directly access `.session`, there's now a function to return the session.
Fence 500's on master for multi-tenant flow without this fix.
Seems like `authlib` decided to make retrieving the `session` an internal function, which seems strange. Perhaps there's a better way to do the access token fetching with the correct redirect. But for now, this is the quick fix

fix(authlib): interface changed, .session is no longer available

---

fence/rbac/client.py
fence/sync/sync_users.py

arborist breaks if you delete the resource, and re-create the resource while not changing the policy that references it. Just wipe all policies for now

fix(arborist): delete policies

---

fence/sync/sync_users.py

Fence usersync gets confused if all the fields in the Project table don't match an update - SqlAlchemy should consider the project-name a primary key - something like that:
```
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) duplicate key value violates unique constraint "project_name_key"
```
Just provide more intuitive message so that user can know how to fix it

PXD-2080 fix(usersync): generate default project name

---

bin/google-user-sa-validation.sh

Add a script to keep running google user sa validation job. The script will exit when any run fail.
- Add a script to keep running google user sa validation job

chore(job): PXD-2307 add google user sa job

---

README.md

1. The OAuth 2.0 RFC and the OIDC spec both establish some well-defined terms that have very particular meanings within those specs. This PR attempts to rewrite the Fence README so that its use of these terms aligns correctly with their definitions in these specs (where before there were a few overloaded or not-well-defined terms). 
2. It also adds further explanation for the diagrams and 
3. makes some phrasing edits for further clarity.

docs(readme): Expand and rewrite to align with OAuth/OIDC terminology

---

requirements.txt

- Fix cirrus error raise to be under Exception
- cirrus 0.2.1 -> 0.2.2

chore(dep): bump cirrus 0.2.2

---

fence/blueprints/data/indexd.py

Fix bug where fence generated new UUID instead of using the same one as indexd.

fix(upload-guid): use same guid for upload

---

fence/blueprints/data/indexd.py

`/data` endpoints previously only checked auth using projects from index ACL;
change this to require a token with a `data` scope for these endpoints.

fix(data-auth): require data scope for endpoints

---

requirements.txt

- fix installation error because a sub-dependancy changed and required a newer version of oauthlib (which we had pinned to an incompatible version), update our pinned version
- oauthlib to 2.1.0

fix(deps): update oauthlib to fix install error

---

README.md
fence/blueprints/data/blueprint.py
fence/sync/sync_users.py
requirements.txt
setup.py
tests/dbgap_sync/data/yaml/user.yaml
ua.yaml

The deployment with the previous fence will run into problems if arborist is rolled after fence, because that will discard the role for data upload which fence creates in it. The solution is to use the user.yaml file and have the fence sidecar to arborist handle the upload role setup.
Differences in user.yaml required for using with arborist: documentation in progress

fix(upload-role): move arborist setup to yaml

---

fence/jwt/keys.py
fence/rbac/client.py

Fixes bug where the app loads keypair directories in the wrong order.
Now will load directories named with timestamps first, sorting those newest to oldest, and then after that, any other directories, in ascending alphabetical order.

fix(key-order): order of JWT keypairs

---

fence/resources/google/validity.py

Fixes this error:
`[  DEBUG] Removing whitelisted SAs None from the SAs on the project xxx.`
`ERROR in error_handler: Catch exception`
`   File "/fence/fence/resources/google/access_utils.py", line 1001, in remove_white_listed_service_account_ids`
`     for email in white_listed_sa_emails:`
`TypeError: 'NoneType' object is not iterable`
- if the config var `WHITE_LISTED_SERVICE_ACCOUNT_EMAILS` is not set, default to an empty list

fix(white-list)

---

requirements.txt

- cirrus -> 0.2.9 for google 403 rate limit error handling

chore(dep): bump cirrus for error handling

---

fence/resources/google/access_utils.py
fence/resources/google/validity.py

https://github.com/uc-cdis/fence/pull/571 defaulted config to empty list but https://github.com/uc-cdis/fence/blob/9f35d0af0c50d840a93c704c9fc05d34d3535e5c/fence/resources/google/access_utils.py#L976 expects it to be None to default to the configuration file. 
overall confusing logic because previously a config was passed through (this is an ugly solution to the issue where fence-create can't rely on flask app config) but new config doesn't rely on that. Should cleanup code to not do this pass-through logic.
- load from config file for google sa validation in every instance of fence-create call
- ensure we're comparings strings to strings for Google parent orgs from config (could be interpretted as ints in the YAML if not correctly quoted)

fix(config): parse from config file if not passed in

---

fence/config-default.yaml
fence/local_settings.example.py
fence/scripting/google_monitor.py
tests/test-fence-config.yaml

Add a flag to the `REMOVE_SERVICE_ACCOUNT_EMAIL_NOTIFICATION` config to disable it
- the email informing users about a service account removal can be enabled/disabled
- the var `REMOVE_SERVICE_ACCOUNT_EMAIL_NOTIFICATION.enable` must be added to the fence config

feat(email-flag)

---

requirements.txt
setup.py

- Get gen3cirrus from PyPI, bump to 0.3.1
- Bump storage-client to 0.2.2

Get gen3cirrus from PyPI, bump storage-client

---

fence/resources/google/utils.py

```
(old_service_account_id, new_service_account["email"].split("@")[:-1])
TypeError: sequence item 1: expected string, list found
```
```
.filter(GoogleServiceAccountKey.email == old_sa_email)
AttributeError: type object 'GoogleServiceAccountKey' has no attribute 'email'
```
- fix 500 errors when creating a service account with prefix

fix(sa-prefix)

---

fence/rbac/client.py
fence/resources/openid/idp_oauth2.py
fence/resources/user/__init__.py
tests/admin/test_admin_groups.py
tests/admin/test_admin_users.py
tests/admin/test_admin_users_endpoints.py
tests/conftest.py
tests/oidc/core/user_info/test_userinfo.py
tests/scripting/test_fence-create.py
tests/session/test_session.py

- User info endpoint will return policy list from arborist for that user, if available.

feat(user-rbac-info): add user policies in info

---

dockerrun.bash
fence/__init__.py
fence/auth.py
fence/blueprints/admin.py
fence/blueprints/data/blueprint.py
fence/blueprints/data/indexd.py
fence/blueprints/google.py
fence/blueprints/link.py
fence/blueprints/login/__init__.py
fence/error_handler.py
fence/jwt/token.py
fence/oidc/endpoints.py
fence/oidc/grants/refresh_token_grant.py
fence/rbac/client.py
fence/resources/google/utils.py
fence/scripting/fence_create.py
fence/sync/sync_users.py
requirements.txt
wsgi.py

todo: update cdislogging tag and authutils tag
tldr: Updated cdislogging. In Fence, **stop using app.logger; only use `get_logger()` from cdislogging**, both to instantiate and to update logger objects. Supply the optional `log_level` argument to `get_logger()` to set logging levels, bearing in mind the tree structure of the loggers. You probably just want to set log level once in `app_config()`, and in all other modules, simply inherit the level and handlers from this parent logger by calling `get_logger()` with no `log_level` arg (which will set level to default NOTSET).
- [PXP-2318] is to set `app.debug` in `app_config()` based on `config["DEBUG"]`.
- However, toggling `app.debug` turns out to toggle not just DEBUG level logging but also INFO and WARNING levels.
- This is because flask …

[PXP-2318] chore(app-debug): Set log level based on config['DEBUG']

---

tests/google/test_service_accounts.py
tests/link/test_link.py

`test_patch_service_account_expires_in` and `test_patch_google_link` occasionally fail by one second. For now, bumping the runtime allowance in those tests and in `test_service_account_registration_expires_in` from 5 to 10 seconds, so that they are not so flakey. 
Doesn't really fall into any category below :(

Bump runtime allowance to 10 seconds from 5

---

bin/fence-create
fence/rbac/client.py
fence/scripting/fence_create.py
fence/sync/sync_users.py
fence/utils.py

This is the same PR as #610, requires uc-cdis/arborist#53.

PXD-2731: Create Arborist client on client-create

---

fence/rbac/client.py
fence/resources/user/__init__.py
fence/sync/sync_users.py
tests/data/test_data.py

- Allow setting policies for `anonymous` and `logged-in` groups in the `user.yaml`.

feat(builtin-groups): support builtin groups in user.yaml

---

fence/blueprints/oauth2.py
fence/error_handler.py
fence/jwt/token.py
fence/oidc/endpoints.py
fence/oidc/grants/authorization_code_grant.py
fence/oidc/grants/implicit_grant.py
fence/oidc/grants/oidc_code_grant.py
fence/oidc/grants/refresh_token_grant.py
fence/oidc/oidc_server.py
requirements.txt
tests/oidc/core/token/test_id_token.py

[v0.10](https://github.com/lepture/authlib/releases/tag/v0.10), [v0.11](https://github.com/lepture/authlib/releases/tag/v0.11)
The `authlib.specs` module was [refactored](https://gist.github.com/lepture/7e38d505c1e22e6e913d8625e5c52cca#file-sp-md) in authlib [0.11](https://github.com/lepture/authlib/releases/tag/v0.11), so this PR changes the import statements.
Fence's `OIDCServer` inherits from `AuthorizationServer` from `authlib.flask.oauth2`. In Authlib 0.9 the `AuthorizationServer`'s `create_authorization_response` method involved [this hack](https://github.com/lepture/authlib/blob/abf4555fa6b0d8cf64c31b2c4c90fb5d875c2de8/authlib/flask/oauth2/authorization_server.py#L231-L233), so in `fence.blueprints.oauth2` we were able to do `response = server.create_authorization_response(user)` …

Update authlib from v0.9 to v0.11

---

fence/models.py
requirements.txt
setup.py
tests/resources/providers.json

the change in tests/resources/providers.json is due to this 
https://docs.sqlalchemy.org/en/12/changelog/migration_12.html#boolean-datatype-now-enforces-strict-true-false-none-values 
the change in fence/models.py in the OIDC migration is due to this 
https://docs.sqlalchemy.org/en/12/changelog/migration_10.html#uniqueconstraint-is-now-part-of-the-table-reflection-process 
bump sqlalchemy 0.9.9 to 1.3.3
bump userdatamodel 1.5.0 to 1.5.1

bump sqlalchemy

---

fence/jwt/token.py

A while ago we stopped using the `flask.current_app` logger and started using the updated `cdislogger` logger everywhere. Apparently I [left](https://github.com/uc-cdis/fence/pull/588/files#diff-7b2574a05fa5500b0a4b10b7b7f23fa0) these checks in the code which are now irrelevant.

fix(log): remove check for capp; became irrelevant upon cdislogging 1.0.0

---

fence/models.py

Upon startup Fence is emitting warnings like this:
```
/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/postgresql/base.py:3289: SAWarning: Predicate of partial index unique_group_project_id ignored during reflection
% idx_name
```
for indices `unique_group_project_id`, `unique_user_group_id`, `unique_user_project_id` (on the `access_privilege` table). 
This is being triggered in the migration code where tables are being loaded in order to inspect their columns:
```table = Table(table_name, metadata, autoload=True, autoload_with=driver.engine)```
and the warning just expresses that SQLAlchemy doesn't know what to do with the predicates (in fact they are just "[where blah is NULL](https://github.com/uc-cdis/userdatamodel/blob/4a63ea3655033631d1623bb9522cd2780bd08e06/userdatamodel/ …

filter SAWarning about not reflecting partial indices

---

fence/config-default.yaml

In the centralized Fence in a Unity Portal deployment, `SESSION_COOKIE_DOMAIN` should be set to `.master.domain.com` in `fence-config.yaml`.
- `SESSION_COOKIE_DOMAIN` is now configurable

feat(unity): support Unity Portal

---

fence/sync/sync_users.py

`_read_file` in sync_users.py was crashing because [`subprocess.Popen`](https://docs.python.org/3.7/library/subprocess.html#subprocess.Popen) was being initialized not in text mode, causing [`Popen.communicate`](https://docs.python.org/3.7/library/subprocess.html#subprocess.Popen.communicate) to return a bytestring while StringIO() expects a string. So dbgap sync broke. 
in usersync _read_file, init Popen with text mode so that output stream is string not bytestring

fix(bytestring): init Popen with text mode

---

fence/sync/sync_users.py

- don't overwrite top-level user.yaml mapping for fence project to arborist resource if no resource path field in individual user projects

fix(sync): dont overwrite top level fence project to arborist mapping

---

fence/resources/google/access_utils.py
tests/google/test_access_utils.py

The `google-delete-expired-service-account` job does not appear to clean out the entries in fence db's `service_account_access_privilege`, so the Google SA will get removed from the GBAG when the link expires, but in `patch_user_service_account()`, the set difference will be empty. Therefore the PATCH call will not re-add the SA to the GBAG. 
So use `granting_project_ids` instead of `to_add` when re-adding SAs to GBAGs. (But continue to use `to_add` in the fence db.) Update tests accordingly. 
Re-add SAs to all GBAGs in PATCH endpoint

[PXP-3384] fix(patch-sa): add all granting_project_ids

---

fence/blueprints/data/indexd.py
requirements.txt

PXP-3646: encode spaces in file names in presigned URLs to follow [RFC 1738](https://www.ietf.org/rfc/rfc1738.txt)
https://github.com/uc-cdis/cdis-python-utils/pull/41
https://github.com/uc-cdis/cirrus/pull/74
- Special characters are encoded in presigned urls
- Bump cdispyutils to 1.0.2, cirrus to 1.1.1

feat(encode-url)

---

fence/models.py

update and fix google_proxy_group_id foreign key check on User table so that delete cascade migration is actually skipped when unnecessary

fix(migrate-check): upd and fix gpgid fkey check

---

fence/config-default.yaml
fence/jwt/token.py

PXP-3717
take this hack for STAGE https://github.com/uc-cdis/fence/compare/fix/3.2.1.x#diff-7b2574a05fa5500b0a4b10b7b7f23fa0
but make number of projects configurable with default 15 and add log
limit projects in token to avoid token being too large

PXP-3717 Fix/token

---

fence/jwt/token.py

I messed up. Need to do this or else the whole `if len(dict(user.project_access)) < config["TOKEN_PROJECTS_CUTOFF"]` thing is pointless. Facepalm
Logically part of this PR  https://github.com/uc-cdis/fence/pull/677

fix(token): actually rm projects from claims before check

---

fence/sync/sync_users.py

https://github.com/uc-cdis/arborist/pull/107 Arborist's PUT policy endpoint is no longer just a delete-create, so Fence usersync can no longer use it as create-but-skip-if-exist
in usersync, instead of put_policy, use create_policy with skip_if_exists arg set to True

fix(create-policy): create and skip if exists

---

fence/sync/sync_users.py
requirements.txt
tests/conftest.py
tests/data/test_data.py

Usersync needs to upsert policies, not create-and-skip-if-exist.
Therefore, in usersync, instead of create_policy, use update_policy with create_if_not_exist set to True
corrects #698 
also bump gen3authz to 0.2.2 and update mocks
in usersync, upsert policies instead of create-and-skip-if-exist. corrects #698

fix(upsert): upsert policies

---

fence/blueprints/login/synapse.py
fence/resources/openid/synapse_oauth2.py

- Use separate users for Synapse with suffix
- Up to date Synapse claims
- Fixed bug that `additional_info` not updating
- Fixed bug that users not in `user.yaml` don't have Arborist users

fix(synapse): fix Synapse issues

---

fence/__init__.py

A tiny refactor we have been meaning to do

chore(refactor): tiny oidc client refactor

---

requirements.txt

From https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html
> Percent-encode all other characters with %XY, where X and Y are hexadecimal characters (0-9 and uppercase A-F). For example, the space character must be encoded as %20 (not using '+', as some encoding schemes do) and extended UTF-8 characters must be in the form %XY%ZA%BC.
see https://github.com/uc-cdis/cdis-python-utils/pull/42
- Whitespaces in AWS S3 signed URL will be escaped as `%20` instead of `+`
- Bump cdispyutils to 1.0.3

PXP-4581 Fix/don't escape whitespaces as + for AWS signed URL

---

fence/models.py
fence/resources/google/validity.py
fence/scripting/fence_create.py
requirements.txt
tests/admin/test_admin_users_endpoints.py
tests/conftest.py
tests/google/test_validity_info.py

This PR fulfills https://ctds-planx.atlassian.net/browse/PXP-4641
Lift up the length limit for username filed, which is causing issues now for users with long email addresses
Works with https://github.com/uc-cdis/userdatamodel/pull/66
- Lift length limit for username filed from 40 to 255 chars
- Bumps userdatamodel to 2.2.0
- Bumps setuptools to at least 40.3.0

PXP-4641 Feat/username limit

---

fence/sync/sync_users.py

Qingya has pointed out that the sync logs can be confusing because they say they are reading from config (which sync does, for cirrus config) but for usersync you can't specify the arborist client in the config, you need to pass in an `--arborist` arg 
add hint in usersync error about arborist client

chore(error-msg): add hint in usersync error

---

fence/blueprints/login/synapse.py
fence/resources/openid/synapse_oauth2.py

Minor changes for Synapse login (BRAIN Dream challenge)
- Fixed an error causing Synapse users' email being incorrectly populated
- Request numerical `userid` from Synapse
-  Use `userid` from Synapse as part of username

(PXP-4777) Feat/synapse userid

---

docs/usersync.md
fence/sync/sync_users.py
requirements.txt
setup.py
tests/dbgap_sync/test_user_sync.py

addresses the following:
- make sure access is revoked when a group is deleted from the user.yaml -> delete all groups that are in the arborist DB but not in the user.yaml
- when a resource is renamed in the user.yaml, the old resource doesn't get deleted and users could still have access to it (e.g. user has access to `/A` and we renamed `/A/B` to `/A/C`) -> can only be reproduced by renaming **top-level** resources, because the "PUT resource" does its job of overriding all the subresources. So users could not still have access to it (the validation check makes sure the resource paths users have access to exist). We can still delete all obsolete resources in the future to clean up the DB but i didn't do it here
- project access in the user.yaml overrides project access in the dbGaP …

PXP-4872 Fix usersync access revoke

---

fence/blueprints/oauth2.py

multi-tenant fence examples for context:
- ORCID login: `/authorize?idp=fence&fence_idp=orcid`
- NIH login in Client Fence: `/authorize?idp=fence&fence_idp=shibboleth&shib_idp=<nih shib ID>`
- NIH login in Server Fence: `/authorize?idp=shibboleth&shib_idp=<nih shib ID>`
- Handle the "fence_idp" query parameter for OIDC clients logging users in through the "/authorize" endpoint

fix(authorize-idp): handle fence_idp in /authorize endpoint

---

requirements.txt
setup.py

Fix build error: httplib2 0.10.3 is installed but httplib2<1dev,>=0.17.0 is required by {'google-api-python-client'}
- httplib2 to 0.17.0

fix(httplib2): httplib2>=0.17.0

---

fence/__init__.py

- when AWS_CREDENTIALS cfg is gone, was trying to use boto when it wasn't setup causing an exception

fix(init): don't try to use boto if it doesn't exist

---

requirements.txt
setup.py

Fence :2020.04 images are failing to produce OIDC client credentials. It throws the following error:
```
Error during connection setup: Error relocating /usr/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: SSLv3_client_method: symbol not found (retrying in 3 seconds)
```
Pinning cryptography 2.8 as this bug only seem to manifest itself with 2.9.

fix(qa): Pin cryptography-2.8 to avoid bug with openssl

---

Jenkinsfile
openapis/swagger.yaml

Updated Swagger Docs for `/user` endpoint and added information about `/.well-known/openid-configuration`
Would probably be easier to review / look at in swagger http://petstore.swagger.io/?url=https://raw.githubusercontent.com/uc-cdis/fence/chore/update-swagger/openapis/swagger.yaml
I didn't include too much detail on the fields in either of these endpoints as they are pretty standard in OIDC and users should refer to the OIDC spec for additional information.
None
Fix docs
Updated documentation to reflect Fence API behavior

PXP-5867 Update OIDC endpoints in swagger

---

fence/sync/sync_users.py

- Recreate built-in groups before granting policies, so that if you remove policies from the built-in groups and run usersync, the groups will get updated accordingly in arborist

PXP-5887 fix(rm-policies-from-grps)

---

fence/__init__.py
fence/config-default.yaml

Fix error at startup for public buckets:
```
S3_BUCKETS:
mybucket:
cred: '*'
```
```
File "/fence/fence/__init__.py", line 218, in _check_s3_buckets
region = app.boto.get_bucket_region(bucket_name, credential)
File "/fence/fence/resources/aws/boto_manager.py", line 108, in get_bucket_region
raise UnavailableError("Fail to reach AWS: {}".format(ex))
fence.errors.UnavailableError: [503] - Fail to reach AWS: Partial credentials found in explicit, missing: aws_secret_access_key
```
- Do not fetch the region at startup for public S3 buckets

fix(public-region): do not check region for public s3 bucket

---

README.md
bin/fence-create
fence/utils.py
tests/scripting/test_fence-create.py

Enable an admin running `fence-create client-create` to specify the allowed scopes when creating a client. Previously a client’s allowed scopes were initialized based on `fence.config.config[“CLIENT_ALLOWED_SCOPES”]`. With this PR, an admin can be more restrictive with what scopes are allowed for a client.
- Enabled `fence-create client-create` to accept space-separated `allowed-scopes` arguments
- Added tests for `fence.scripting.fence_create.create_client_action`

PXP-4787 Enable allowed scopes to be specified in fence-create’s client-create command

---

fence/config-default.yaml
fence/resources/openid/google_oauth2.py
tests/login/test_google_login.py

Enable a user who has access to a large number of projects to be able to login successfully when loading the Gen3 authorization page. Previously, for users with access to too many projects, attempting to login and load the authorization page resulted in 502 and 400 errors.

PXP-5256 Fix broken authorization page login for users with many projects

---

fence/sync/sync_users.py
requirements.txt
setup.py

Q: Mightn't we as well validate actual _provided_ emails including deliverability checks??
A: Not in usersync; if at all, then in useryaml validation
- In usersync, populate user email iff email is provided in useryaml OR username is an email addr
- Usersync will no longer populate user's email field in Fence db with the user's username, UNLESS the username is an email address, in which case previous behavior applies (email field is populated with the username). In other words, nothing should change except in cases where usersync was putting invalid emails into user email fields anyway. 
- Added dependency email_validator v1.1.1

PXP-2802 feat(usync-emails)

---

requirements.txt
setup.py

Add back the changes from https://github.com/uc-cdis/fence/pull/783 that got inadvertently removed by https://github.com/uc-cdis/fence/pull/745
Also, pin `awscli` dependency (@diw2 could you check if that version is fine?)
- Fix dependencies so pip parses correctly
- storage-client to 1.0.1

re-fix dependencies

---

fence/blueprints/login/ras.py
fence/models.py
fence/resources/openid/ras_oauth2.py
fence/resources/user/__init__.py

~(This needs to be rebased--currently branched off RAS IDP branch. To review, just select the last few commits in the differ)~
~(Not actually doc-only, but want to skip tests until rebase is done)~
- Add ga4gh_visa_v1 table to database
- Save user's RAS visas to db upon RAS login
- Include ga4gh_passport_v1 claim in userinfo response

PXP-6240 Support ga4gh passport claim in userinfo

---

fence/blueprints/oauth2.py
fence/jwt/token.py
fence/oidc/jwt_generator.py
tests/oidc/core/token/test_id_token.py

- Include at_hash claim in id tokens where an access token is issued alongside
- Refactor UnsignedIDToken class in order to use both CodeIDToken and ImplicitIDToken from Authlib
- id token validation is now sensitive to present auth flow type (some claims like nonce and at_hash are validated differently in implicit vs code flow)

PXP-2799 Access token hash

---

fence/blueprints/login/ras.py

- Clear user ga4gh visas upon login, before fetching new ones; assumes RAS is sole visa issuer for now.

fix(clear-user-visas): clear user visas on login before fetch

---

fence/oidc/grants/oidc_code_grant.py

- Use authorization_code object saved in Grant class attributes; remove unnecessary db query

refactor(auth-code): use code from Grant class attrs

---

fence/scripting/fence_create.py

~(I'm pretty sure nothing uses the output of this command programmatically~
Note: gen3-qa and cloud-auto use the fence-create client-create output programmatically, but they take the last line of output. So this PR keeps the last line of output the same. 
Improve output for fence-create client-create (label the id/secret, add instructions to save the creds)

fix(client-create-output): Improve output for fence-create client-create

---

TECHDEBT.md
fence/config-default.yaml
fence/jwt/token.py
fence/resources/user/__init__.py
tests/oidc/core/token/test_token_response.py

Also introduces a techdebt.md 
- Add new 'scopes' claim to access tokens (for GA4GH AAI); add ga4gh_passport_v1 to user/session scopes
- Make (for now only one of the) claims returned in userinfo responsive to scopes present in access token

PXP-6406 Feat/ga4gh scope

---

docs/fence_shibboleth.md

Issue found when deploying Fence 2020.05 to KF (which was previously using 4.8.0)
- Document misconfigured NIH login issue

Document NIH login issue

---

fence/config-default.yaml
fence/jwt/token.py
fence/resources/openid/ras_oauth2.py

It does not seem like the `ras_dbgap_v1` scope its being used since not having the scope does not change anything. It is also not mentioned anywhere in the NIH RAS dev guides. 
- Added `ga4gh_passport_v1` scope description. 
- removed `ras_dbgap_v1` scope.

Add ga4gh scope description

---

fence/oidc/endpoints.py
openapis/swagger.yaml
tests/rfc6749/test_revoke.py

- token revocation per RFC 7009 should return 200 even if the token is expired

fix(token-revoke): correct behavior to match RFC 7009, 200 on revoke of invalid token

---

Dockerfile

Update fence's base image to enable an Nginx Status endpoint.
This is small / harmless change required to unblock a `cloud-automation` PR: https://github.com/uc-cdis/cloud-automation/pull/1348
- New base image `pybase3-1.3.0`
- This Nginx status endpoint is a hard dependency for the `nginx-prometheus-exporter` side car. Any older fence image that is used with the Kubernetes deployment descriptor that is declared with the sidecar below will fail to come up.
```
- name: nginx-prometheus-exporter
image: registry.hub.docker.com/nginx/nginx-prometheus-exporter:0.8.0
args: ["-nginx.scrape-uri", "http://127.0.0.1/nginx_status"]
ports:
- containerPort: 9113
```

chore(monitoring): Adopt new pybase img version.

---

fence/blueprints/login/base.py
fence/errors.py

- Implemented a redirect to fence client specified `redirect_uri` when you deny consent from any idp.

(PXP-6507): Handle denied access from any IDP

---

Dockerfile
README.md

Update fence's base image to enable Status endpoints and aggregated metrics to be scraped by Prometheus.
- New base image `pybase3-1.4.0`

chore(observability): Adopt latest py base img

---

fence/jwt/token.py
tests/jwt/test_tokens.py

GA4GH AAI requires that client ID be in `aud` in the access token if the `aud` claim is provided. Adding client id and also adding a test to check for compatibility with GA4GH spec. 
This might impact our existing validation if we're checking for audiences.

Add Client_ID to Audiences

---

bin/fence-create
fence/__init__.py
fence/resources/google/access_utils.py
fence/resources/openid/idp_oauth2.py
fence/scripting/fence_create.py
fence/scripting/google_monitor.py
fence/sync/sync_users.py
tests/google/test_access_utils.py
tests/google/test_service_accounts.py
tests/link/test_link.py
tests/login/test_google_login.py
tests/scripting/test_fence-create.py

- Added functionality to modify `allowed_scopes` to existing clients using `fence-create client-modify --client CLIENT_NAME --allowed-scopes NEW_SCOPE`
- Added functionality to append `allowed_scopes` to existing clients using `fence-create client-modify --client CLIENT_NAME --allowed-scopes NEW_SCOPE --append`
- Added functionality to append `urls` to existing clients using `fence-create client-modify --client CLIENT_NAME --urls NEW_URL --append`

(PXP-6618) Use fence-create to modify urls and allowed scopes.

---

requirements.txt

To resolve `error: six 1.11.0 is installed but six<2dev,>=1.13.0 is required by {'google-api-python-client'}`. Pinned google-api-python-client in cirrus [uc-cdis/cirrus#82](https://github.com/uc-cdis/cirrus/pull/82)
- Change gen3cirrus to >=1.2.0

fix(dependency): pin cirrus

---

fence/blueprints/login/base.py

Hitting the 'Deny' button in the consent screen for NIH RAS would redirect you back to the `/authorization` endpoint which in turn would take you back to the RAS Consent Screen when you go through this flow using a different client than the windmill client. 
- Fixed consent Deny redirecting users back to the consent screen.

Fix: Consent deny redirect bug

---

requirements.txt

Removing `six` from requirements.txt
This was creating an issue in building the Fence image in Quay

fix: remove SIX from requirements.txt

---

fence/blueprints/google.py

- Fixed google service account dry run for `/patch` throwing 500 instead of 400 when exceeding allowed number of projects.

Fix(service account): dry_run error handling

---

fence/resources/openid/ras_oauth2.py

Currently, we look for `UserID` for username from RAS's userinfo payload. This is specified in the [RAS's Userinfo Paylod](https://auth.nih.gov/docs/RAS/serviceofferings.html#AppendixA). However, they are sending us `UserID` for eraCommons users and `userid` for NIH users.
We want to support both of these for now and remove `UserID` later on once RAS adds a fix to only use `userid`. 
- add support for `userid` from RAS userinfo payload as a valid username.

Add support to accept userid in RAS

---

fence/scripting/fence_create.py

Our `fence-create google-manage-keys` CLI command is returning 400 FAILED_PRECONDITION while attempting to delete a key that no longer exists in GCP (only exists in fence's database).
The description from the official documentation is quite misleading... 🤔 
https://cloud.google.com/apis/design/errors
> 400 FAILED_PRECONDITION Resource xxx is a non-empty directory, so it cannot be deleted.
logs:
```
{
"error": {
"code": 400,
"message": "Precondition check failed.",
"status": "FAILED_PRECONDITION"
}
}
>
ERROR: (gcloud.iam.service-accounts.keys.delete) FAILED_PRECONDITION: Precondition check failed.
```
Because it is trying to delete a key that no longer existing in Google Cloud. Hence we should just allow the CLI operation to delete the orphan key in fence's db and unblock the Continuous …

chore(google-manage-keys): Handle key deletion attempt that returns 400 FAILED_PRECONDITION

---

fence/__init__.py
fence/utils.py
poetry.lock
tests/link/test_link.py
tests/login/test_google_login.py
tests/session/test_session.py
tests/test_logout.py

- make sure to set httponly on all cookies

feat(cookies): always set httponly flag on cookies (also update deps) PXP-7593

---

fence/__init__.py

Jira Ticket: [PXP-7319](https://ctds-planx.atlassian.net/browse/PXP-7319)
This is a small bug fix so that `fence` idp is not required in `LOGIN_OPTIONS` config in order for `fence` idp oauth flow to work. `LOGIN_OPTIONS` is actually intended to be used for configuring which login buttons to show on the frontend. Please see ticket above for more details.
- Fix oauth flow to work even when fence idp not in LOGIN_OPTIONS config

(PXP-7319): Fix oauth flow when fence idp not in LOGIN_OPTIONS

---

README.md

closes #879
thanks @ndjones!
- Fix broken link: reference to the #create-user-access-file readme section

docs(Accessing Data): Fixed broken link to #create-user-access-file

---

.secrets.baseline
fence/templates/error.html
fence/templates/oauthorize.html

This PR fulfills https://ctds-planx.atlassian.net/browse/PXP-7597
An Outdated jQuery Library vulnerability has been identified by PenTest
Removed some jQuery and Bootstrap import if not needed. Also migrated jQuery in need from  1.11.3 to 3.6.0
Deployed and tested in https://qa-mickey.planx-pla.net
- bump up jQuery for remediating Outdated jQuery Library vulnerability

PXP-7597 Fix outdated jQuery

---

fence/blueprints/login/ras.py
fence/job/visa_update_cronjob.py
fence/resources/openid/idp_oauth2.py

This was an ask from ISB-CGC. It's mostly for testing purposes. Basically [#848](https://github.com/uc-cdis/fence/pull/848) but for RAS or any other Visa provider we might have in the future. 
- Added `upstream_expires_in` parameter in the `/authorization` endpoint to manually add refresh token expiration time. 
- Fixed Visa Update cronjob not clearing expired refresh tokens.

(PXP-7846): Visa refresh token expiration parameter

---

.secrets.baseline
fence/blueprints/data/indexd.py
tests/conftest.py
tests/data/test_data.py

Jira Ticket: [PXP-7447](https://ctds-planx.atlassian.net/browse/PXP-7447)
Fix bug when hitting the `/data/upload/<guid>` endpoint for a record with no existing URLs:
```
File "/fence/fence/blueprints/data/blueprint.py", line 290, in upload_file
result = get_signed_url_for_file("upload", file_id, file_name=file_name)
File "/fence/fence/blueprints/data/indexd.py", line 83, in get_signed_url_for_file
protocol=requested_protocol, indexed_file=indexed_file, action=action
File "/fence/fence/blueprints/data/indexd.py", line 98, in create_presigned_url_audit_log
protocol = indexed_file.indexed_file_locations[0].protocol
IndexError: list index out of range
```
and add upload test case for a record with no existing URLs
- Do not try to record audit logs for upload presigned URLs - fixes issue when …

PXP-7447 Do not try to record audit logs for upload presigned URLs

---

.secrets.baseline
fence/blueprints/data/indexd.py
tests/conftest.py
tests/data/test_data.py

Jira Ticket: [PXP-6693](https://ctds-planx.atlassian.net/browse/PXP-6693)
With the old logic for generating a signed url for public records, Fence did not allow upload urls to be generated for records with public `authz` or `acl` values ("/open" and "*", respectively). However, users with a `write-storage` permission on "/open" for Fence should be permitted to generate upload urls.
- Allow permitted users to generate a signed upload url for public records (i.e. those records with `authz=[“/open”]`)

(PXP-6693): Fix generation of signed upload urls for public Indexd records for authz-permitted users.

---

.secrets.baseline
openapis/swagger.yaml

- Swagger doc: add fence_idp to /oauth2/authorize endpoint

Swagger doc: add fence_idp to /oauth2/authorize endpoint

---

.github/workflows/wool.yml
fence/__init__.py

The GITHUB_TOKEN provided automatically in GitHub workflows only has "read" access when a workflows runs on a fork (see https://github.community/t/github-actions-are-severely-limited-on-prs/18179#M9249), so it's blocking our tests on PRs from external contributors. Switch to using `PLANXCYBORG_GITHUB_TOKEN` which will always have write access

Use PLANXCYBORG_GITHUB_TOKEN instead of GITHUB_TOKEN

---

.github/workflows/wool.yml

* Use GITHUB_TOKEN for wool in CI

fix(ci-token): use GITHUB_TOKEN

---

README.md
fence/__init__.py
fence/blueprints/login/__init__.py
fence/blueprints/login/cilogon.py
fence/config-default.yaml
fence/resources/openid/cilogon_oauth2.py
tests/login/test_login_redirect.py
tests/test-fence-config.yaml
tests/test_audit_service.py

First commit of CILogon authentication. CILogon provides a
standards-compliant OpenID Connect (OAuth 2.0) interface to federated
authentication including InCommon, the Australian Access Federation
(AAF), and eduGAIN. CILogon OpenID Connect (OIDC) client registration
is available to researchers and scholars at
https://cilogon.org/oauth2/register
Add CILogon as an authentication option. CILogon provides a standards-compliant OpenID Connect (OAuth 2.0) interface to federated authentication including InCommon, the Australian Access Federation (AAF), and eduGAIN. CILogon OpenID Connect (OIDC) client registration is available to researchers and scholars at https://cilogon.org/oauth2/register

First commit of CILogon authentication

---

fence/jwt/validate.py

Jira Ticket: n/a
Here's a funny one :D It has been around for a minute! 
Uncovered when trying to run two Fences. The user_session code checks the incoming session token and calls the validation code with the app's own public key; this should _not_ use any other public key than the app's own. So the validate function needs to respect the arg. 
Fix fence.jwt.validate so it uses the public_key argument

fix(pkey-from-arg): Respect public_key arg

---

fence/oidc/grants/refresh_token_grant.py

Jira Ticket: n/a
If the token request with refresh token grant does not contain a "scope" query arg, then this part of the code will throw a KeyError when dealing with an old token with no scope claim. 
- Fix backwards compatibility for old refresh tokens without scopes. (Note: 5.0.0 claimed to be backwards compatible with old refresh tokens, but was missing this patch)

Fix backwards compatibility for old refresh tokens without scopes

---

fence/blueprints/login/fence_login.py

There exist people running multi Fence with two modern Fences!
Jira Ticket: n/a
- Fix ID token validation for multi-tenant Fence setup: Allow both old and new style ID tokens
- Fix ID token validation for multi-tenant Fence setup: Client Fence should demand its client_id, not its BASE_URL, in the aud claim

fix(multifence-validation): allow old AND new style id tokens

---

Dockerfile
pyproject.toml

Suppressing UWSGI & NGINX metrics in favour of DataDog’s telemetry / python APM / probing -- hoping we can achieve the same observability with it.
- Once we retire the k8s sidecar containers from fence's k8s YAML (here: https://github.com/uc-cdis/cloud-automation/pull/1643), old fence images will face a lot of log noise as the HTTP metrics endpoints will no longer exist.

chore(pybase3): Update pybase img de novo

---

.secrets.baseline
fence/__init__.py
fence/blueprints/data/indexd.py
fence/config-default.yaml
fence/resources/audit/client.py

Jira Ticket: [PXP-8318](https://ctds-planx.atlassian.net/browse/PXP-8318)
- Split the private fields from the public fields in the audit logging configuration
- When deciding whether to sign a URL for download, do not rely on "acl" if the record has an "authz"

PXP-8318 Split public and private audit configs

---

fence/blueprints/well_known.py

- Fix the `/.well-known/openid-configuration` endpoint to always return the environment's base URL in the `issuer` field, instead of returning the upstream Fence IDP's base URL

Well known endpoint: issuer is always base URL

---

.secrets.baseline
fence/blueprints/login/__init__.py
fence/blueprints/oauth2.py
tests/conftest.py
tests/login/test_fence_login.py
tests/test-fence-config.yaml

Jira Ticket: [PXP-9099](https://ctds-planx.atlassian.net/browse/PXP-9099)
Fix bug causing a redirection to the default NIH entity ID instead of the custom entity ID when users login through the oauth2 flow WITHOUT SPECIFYING AN IDP.
The config below should redirect to the "X" provider when users log into Gen3 via a client portal which does not specify the IDP, but it redirects to "urn:mace:incommon:nih.gov" instead (default "shib_idp") because the "shib_idp" param is not passed to centralized fence.
```
DEFAULT_LOGIN_IDP: fence
LOGIN_OPTIONS:
- name: 'NIH Login'
idp: fence
fence_idp: shibboleth
shib_idps:
- X
```
- Fix the redirection to the default IDP in the `/oauth2/authorize` endpoint: when the default IDP is "fence", include `idp` and `shib_idp` query parameters
- Update the unit …

PXP-9099 Fix redirection to default IDP in oauth2 flow

---

fence/blueprints/login/base.py

bug introduced in 5.5.2
- Fix issue with IdP subject being sent to audit log on login instead of Gen3 subject

fix(audit): fix audit log to send Gen3 sub instead of idp sub

---

fence/config-default.yaml

* `visa_types` should be strings

fix: visa_types in fence-config should be strings

---

fence/models.py

Add `authz` column to `project` table during migration. Corresponds with https://github.com/uc-cdis/userdatamodel/pull/74.

chore(migration): add authz column to project

---

fence/auth.py
fence/blueprints/login/__init__.py
fence/blueprints/oauth2.py
fence/config-default.yaml

Fix errors caused by the value for `ENABLED_IDENTITY_PROVIDERS` being None in the default fence config and gen3 community members' fence configs
```
Details: {'message': "argument of type 'NoneType' is not iterable"}
[2022-02-01 17:49:50,479][fence.error_handler][  ERROR] Catch exception
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/fence/fence/auth.py", line 198, in wrapper
"ENABLED_IDENTITY_PROVIDERS", {}
AttributeError: 'NoneType' object has no attribute 'get'
```
- Fix ENABLED_IDENTITY_PROVIDERS errors caused by the …

Fix ENABLED_IDENTITY_PROVIDERS errors

---

fence/resources/storage/__init__.py

- Fix granting of storage access so that `expires` is honored

fix(grant storage access): honor `expires`

---

.secrets.baseline
tests/conftest.py
tests/dbgap_sync/conftest.py

Jira Ticket: [PXP-10115](https://ctds-planx.atlassian.net/browse/PXP-10115)
Please see ticket comment for more background on what is causing flakiness.
- Fix `test_user_sync_with_visa_sync_job` flakiness by generating unique `jti`, `txn` fields for every mocked passport

(PXP-10115): fix test_user_sync_with_visa_sync_job flakiness

---

fence/__init__.py
fence/blueprints/data/blueprint.py
fence/blueprints/data/indexd.py
fence/config-default.yaml
fence/resources/audit/client.py
openapis/swagger.yaml
tests/data/test_blank_index.py
tests/data/test_data.py
tests/test-fence-config.yaml
tests/test_app_config.py

Fixes and closes #1048
- Allow specifying the bucket to upload to (endpoints `/data/upload` and `/data/upload/<GUID>`)
- Configure the `ALLOWED_DATA_UPLOAD_BUCKETS` setting to allow users to upload to buckets other than `DATA_UPLOAD_BUCKET`
- Return a 500 error instead of a 401 error when an S3 bucket is not configured properly

PXP-10361 Allow specifying the upload bucket

---

.secrets.baseline
README.md
bin/fence_create.py
fence/models.py
fence/scripting/fence_create.py
fence/utils.py
tests/scripting/test_fence-create.py

Jira Tickets: [PXP-10250](https://ctds-planx.atlassian.net/browse/PXP-10250) and [PXP-10268](https://ctds-planx.atlassian.net/browse/PXP-10268)
Goes with https://github.com/uc-cdis/cloud-automation/pull/2075
- Add `--expires-in` parameter to the `fence-create` `client-create` and `client-modify` commands to specify the number of days in which in a client expires
- Add the `fence-create client-delete-expired` command to remove expired OIDC clients and optionally post warnings in Slack

PXP-10250 PXP-10268 OIDC clients expliration

---

fence/scripting/fence_create.py

```
[2023-03-08 22:20:53,211][fence.scripting.fence_create][   INFO] No project with auth_id QA found. No linking occured.
Traceback (most recent call last):
File "/usr/local/bin/fence-create", line 6, in <module>
sys.exit(main())
File "/fence/bin/fence_create.py", line 536, in main
create_or_update_google_bucket(
File "/fence/fence/scripting/fence_create.py", line 1360, in create_or_update_google_bucket
bucket_db_entry = _create_or_update_google_bucket_and_db(
File "/fence/fence/scripting/fence_create.py", line 1505, in _create_or_update_google_bucket_and_db
project_id=project_db_entry.id, provider_id=google_cloud_provider.id
AttributeError: 'NoneType' object has no attribute 'id'
```
- Fix `fence-create google-bucket-create` when the project does not exist

Fix fence-create google-bucket-create

---

fence/config-default.yaml
fence/resources/google/access_utils.py
fence/utils.py

Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- add backoff to Google Group API calls

feat(backoff): add backoff to Google Group API calls

---

fence/config-default.yaml
fence/config.py

- Allow setting `INDEXD_PASSWORD` via environment variable.

allow setting INDEXD_PASSWORD via env var

---

fence/blueprints/data/indexd.py
fence/sync/sync_users.py

Jira Ticket: [PXP-10920](https://ctds-planx.atlassian.net/browse/PXP-10920)
If we hit the Fence `DELETE /data/<GUID>` endpoint with a GUID without prefix, the indexd record is fetched successfully (GUID resolution without prefix) and the file is deleted from the bucket, but fence fails to delete the indexd record itself (the deletion endpoint does not accept a GUID without prefix).
- The `DELETE /data/<GUID>` endpoint now supports resolving and deleting a GUID without its prefix
[PXP-10920]: https://ctds-planx.atlassian.net/browse/PXP-10920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-10920 Support deleting data without GUID prefix

---

.secrets.baseline
fence/__init__.py
fence/resources/google/utils.py
fence/scripting/fence_create.py
fence/sync/sync_users.py
fence/utils.py
migrations/versions/e4c7b0ab68d3_create_tables.py
tests/dbgap_sync/conftest.py
tests/scripting/conftest.py
tests/scripting/test_fence-create.py

```
ERROR:SQLAlchemyDriver:Fail to setup database tables, continue anyways
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/userdatamodel/driver.py", line 28, in __init__
self.setup_db()
File "/usr/local/lib/python3.9/site-packages/userdatamodel/driver.py", line 36, in setup_db
self.pre_migrate()
File "/usr/local/lib/python3.9/site-packages/userdatamodel/driver.py", line 88, in pre_migrate
if not self.engine.dialect.has_table(
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3593, in has_table
self._ensure_has_table_connection(connection)
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 342, in _ensure_has_table_connection
raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: The …
```

Fix SQLAlchemyDriver warning

---

.secrets.baseline
.travis.yml
docs/fence_multifactor_authentication_guide.md
fence/blueprints/link.py
fence/blueprints/login/base.py
fence/blueprints/login/ras.py
fence/config-default.yaml
fence/config.py
fence/resources/openid/cilogon_oauth2.py
fence/resources/openid/cognito_oauth2.py
fence/resources/openid/google_oauth2.py
fence/resources/openid/idp_oauth2.py
fence/resources/openid/microsoft_oauth2.py
fence/resources/openid/okta_oauth2.py
fence/resources/openid/orcid_oauth2.py
fence/resources/openid/ras_oauth2.py
fence/resources/openid/synapse_oauth2.py
fence/resources/user/user_session.py
fence/sync/sync_users.py
tests/conftest.py
tests/dbgap_sync/conftest.py
tests/dbgap_sync/test_user_sync.py
tests/link/conftest.py
tests/login/test_base.py
tests/login/test_idp_oauth2.py
tests/login/test_microsoft_login.py
tests/test_audit_service.py
travis/pg_hba.conf
travis/postgresql.conf

Adds the mfa_policy on login when the configured claim and value are present in the user's id_token.
- Enables support for identifying when users have authenticated with MFA.  
- Deployment changes to enable this feature for commons are described here https://github.com/uc-cdis/fence/blob/e36f6574ade17bb8c9c0c9df8801f9a59de423b1/docs/fence_multifactor_authentication_guide.md

feat(DCF-1446): Assign MFA policy on login

---

fence/blueprints/data/blueprint.py
fence/blueprints/data/indexd.py
fence/blueprints/ga4gh.py
fence/resources/audit/utils.py
tests/test_audit_service.py

- Downloads through GA4GH DRS are recorded in audit service

Downloads through GA4GH DRS are recorded in audit service

---

.secrets.baseline
fence/resources/user/__init__.py
tests/conftest.py
tests/oidc/core/user_info/test_userinfo.py
tests/test_logout.py

Link to JIRA Issue: [PXP-11181](https://ctds-planx.atlassian.net/browse/PXP-11181)
- Fixes issue where users not present in arborist would have blank resources and authz fields when they should have values for open access data within the commons. 
[PXP-11181]: https://ctds-planx.atlassian.net/browse/PXP-11181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pull resources from auth_mapping

---

fence/sync/sync_users.py
tests/dbgap_sync/test_user_sync.py

- Fixes issue with usersync and MFA policy management in cases where a user has not been persisted by Fence.

Fix MFA policy management with unknown users

---

fence/blueprints/data/indexd.py

When creating an indexd record the default value for `size` is `None`
`.get()` will only returns the default if the key doesn't exists, but in this case, it will returns `None`
This fixes above mentioned issue
- Fixed a bug causing the metadata ingestion CI test to fail

fix get returns none type

---

poetry.lock
pyproject.toml

[PPS-809](https://ctds-planx.atlassian.net/browse/PPS-809)
* cryptography to 42.0.5
[PPS-809]: https://ctds-planx.atlassian.net/browse/PPS-809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(PPS-809): upgrade cryptography to 42.0.5

---

fence/sync/sync_users.py

Link to JIRA ticket if there is one:  [PXP-11364](https://ctds-planx.atlassian.net/browse/PXP-11364)
- Fix so local csvs file are processed in consistent order, regardless of os
- Updates user_info overwrite logic to preserve data when processing CSVs without some attributes
[PXP-11364]: https://ctds-planx.atlassian.net/browse/PXP-11364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-11364 handle csv ordering with userinfo

---

fence/__init__.py
fence/blueprints/data/blueprint.py
fence/blueprints/data/multipart_upload.py
fence/resources/aws/boto_manager.py
tests/data/test_boto_manager.py

Link to JIRA ticket if there is one: N/A
- Adds support for deleting files from non-AWS S3-compatible endpoints (e.g. MinIO, Wasabi, Ceph).
- Fixes the "The AWS Access Key Id you provided does not exist" error when attempting to delete a file from a non-AWS bucket.
- Allows for Gen3 administrators to have greater flexibility in choosing their preferred data storage, while keeping the AWS S3 endpoint as the "default" storage option.

Automated copy feat/s3 delete files

---

fence/auth.py
fence/config-default.yaml
fence/config.py
tests/login/test_login_user.py

Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/VADC-1255
- feat: new config option to allow only existing OR active users to login
- activation of the feature depends on a new configuration setting: `ALLOW_NEW_USER_ON_LOGIN`

Feat: only allow login of onboarded users

---

fence/oidc/oidc_server.py

- Fix typo in ClientAuthenication log

Fix typo in ClientAuthenication log

---

.github/workflows/integration_tests.yaml
fence/sync/sync_users.py
pyproject.toml

While changing from mcrypt to ccrypt, we didn't add `stdout` for the result of `ccdecrypt`. So we would decrypt the file but not output the file to somewhere its readable. 
- Fixed usersync decrypted result not parsing

(Fix): Usersync ccdecrypt output not parsing

---

tests/ci_commands_script.sh
tests/utils/metrics.py

Before any prometheus unit test runs, check that prometheus is configured correctly, instead of getting hard to debug errors when it's not.
I added a new env var `PROMETHEUS_CONFIGURED_FOR_TESTS` because we can't rely on the existing `PROMETHEUS_MULTIPROC_DIR`; the tests can fail even when it's set ([here](https://github.com/uc-cdis/fence/blob/7b0aa60/fence/metrics.py#L45)) if it hasn't been set _before_ the tests started running.

Unit tests: check that Prometheus is configured correctly

---

migrations/README.md

Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/CADC-1795
- The assumption that all migrations are executed automatically on startup is not correct, and therefore it is crucial that the README of a PR in Fence that adds a migration, ALWAYS contains a “Deployment changes” section. 
- This PR adds a warning README in the /migrations folder to warn future developers about this.

fix: add a note in the migrations folder alerting about the manual migration possibility

---

fence/resources/audit/utils.py
tests/admin/test_admin_users_endpoints.py

Fix bug introduced in #1234 when using client_credentials tokens to hit admin endpoints:
```
Traceback: Traceback (most recent call last):
File "/fence/.venv/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
rv = self.dispatch_request()
File "/fence/.venv/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
File "/fence/fence/authz/auth.py", line 91, in wrapper
return f(*f_args, **f_kwargs)
File "/fence/fence/resources/audit/utils.py", line 128, in wrapper
create_log_for_request(flask.request)
File "/fence/fence/resources/audit/utils.py", line 103, in create_log_for_request
username = get_user_from_claims(claims).username
File …
```

Admin endpoints support "client_credentials" tokens again

---

fence/blueprints/login/__init__.py
fence/blueprints/privacy.py

After the cache expires, `cache.add()` does nothing, because the key still technically exists, it's just expired. Need to use `cache.set()` instead.
```
from cachelib import SimpleCache
CACHE = SimpleCache(default_timeout=1)
cache_key = "abc"
if not CACHE.has(cache_key):
CACHE.add(cache_key, 123)
import time; time.sleep(2)
if not CACHE.has(cache_key):
CACHE.add(cache_key, 123)
print(CACHE.get(cache_key))  # ==> prints "None"
if not CACHE.has(cache_key):
CACHE.set(cache_key, 123)
print(CACHE.get(cache_key))  # ==> prints "123"
```
Fix this error:
```
File "/fence/fence/blueprints/login/__init__.py", line 298, in get_login_providers_info
all_provider_info = [
File "/fence/fence/blueprints/login/__init__.py", line 299, in <listcomp>
get_provider_info(login_details) for login_details in …
```

Fix `/login` providers cache
