README.md

feat(badges): add badges to README

---

setup.py

fix(setup.py): add pyyaml dependency

---

bin/fence-create
dev-requirements.txt
fence/__init__.py
fence/blueprints/storage_creds.py
fence/local_settings.example.py
fence/resources/storage/__init__.py
fence/resources/userdatamodel/__init__.py
fence/sync/sync_dbgap.py
tests/dbgap_sync/conftest.py
tests/dbgap_sync/data/authentication_file_phs000178.txt
tests/dbgap_sync/data/authentication_file_phs000179.txt
tests/dbgap_sync/test_dbgap_sync.py
tests/test_settings.py

add script to sync from dbgap to both database and storage backends
depends on https://github.com/uc-cdis/cdisutils-test/pull/5

feat(dbgap): add dbgap syncing script

---

setup.py

fix(message): fix unclear err message

---

bin/fence-create
fence/blueprints/storage_creds.py
fence/data_model/models.py
fence/resources/storage/cdis_jwt.py
tests/conftest.py
tests/test_cdis.py

Added new table 'refresh_token' to DB
- insert new refresh token whenever new token is generated
- query the table to obtain refresh token
@thanh-nguyen-dang , @rudyardrichter , @philloooo

fix(cdis_refresh_token): Fix mising of refresh_token for cdis backend

---

fence/blueprints/data.py
fence/blueprints/storage_creds.py
fence/resources/aws/boto_manager.py
openapi/swagger.yaml
run.py

- fix swagger doc
- add `init_oauth` into `run.py` to enable session
@philloooo

fix(doc-run): fix run.py and swagger doc

---

fence/auth.py
fence/jwt/token.py
fence/settings.py
tests/test_oauth2.py
tests/test_settings.py
tests/utils/__init__.py

we were using both HOST_NAME and HOSTNAME ...
counting on travis to run the test suite for me ... :-)

fix(HOSTNAME): replace HOST_NAME

---

fence/auth.py
fence/jwt/token.py
fence/oidc/__init__.py
fence/resources/storage/cdis_jwt.py
requirements.txt
setup.py
tests/oauth2/test_id_token.py
tests/oauth2/test_oauth2.py

Trimmed unnecessary access/refresh token fields
Used bare bones implementation of IDToken from Authlib and patched extra stuff on top. Minimal testing, should be expanded further once all the OIDC stuff gets merged together

feat(id-token): initial addition of ID token

---

fence/blueprints/oauth2.py
fence/blueprints/storage_creds.py
fence/data_model/models.py
fence/jwt/blacklist.py
fence/jwt/token.py
fence/resources/storage/cdis_jwt.py
tests/test_cdis.py
tests/utils/cdis.py

- add `exp` to return value of list and parameter to delete
- change `exp` from DateTime to BigInt for `user_refresh_token` table
r @philloooo @rudyardrichter

fix(list): fix list api add exp

---

fence/auth.py
fence/blueprints/storage_creds.py
fence/resources/storage/cdis_jwt.py
tests/test_cdis.py
tests/test_credentials.py
tests/utils/cdis.py

fix(list): fix to use request.data

---

fence/auth.py
fence/blueprints/login.py

- setattr doesn't work for dict
- add a shibboleth session setup endpoint
- add docstring for login flow
TODO:
https://github.com/uc-cdis/fence/issues/75

fix(shib): fix redirect flow

---

fence/jwt/token.py
fence/oidc/oidc_server.py
requirements.txt
setup.py

remove our patch of auth grant function (fixed in authlib)

chore(deps): update authlib to 0.4.1

---

fence/jwt/keys.py
tests/rfc7517/test_jwks.py

fix to follow https://tools.ietf.org/html/rfc7517#appendix-A.1

fix(jwks): base64url encode exponent and modulus

---

bin/fence-create
fence/blueprints/oauth2.py
fence/jwt/token.py
fence/local_settings.example.py
fence/settings.py
fence/templates/oauthorize.html
tests/rfc6749/test_oauth2.py

allow creating oidc client that needs user's consent

chore(fence-create): allow creating external client

---

openapi/swagger.yaml

[Rendered docs here](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/uc-cdis/fence/docs/jwks/openapi/swagger.yaml#/keys)

docs(jwks): add jwks endpoint in openapi docs

---

fence/jwt/validate.py

claims will not be assigned if exception is raised

fix(errorlog): decode provided token

---

fence/blueprints/data.py
fence/blueprints/login/__init__.py
fence/errors.py
fence/local_settings.example.py
fence/oidc/endpoints.py
fence/resources/aws/boto_manager.py
fence/settings.py
requirements.txt
setup.py
tests/conftest.py
tests/test_settings.py

r @philloooo @rudyardrichter 
this pr depend on the pr below
https://github.com/uc-cdis/cdis-python-utils/pull/24

feat(user): add user_id, username to presigned_url

---

fence/jwt/token.py
fence/local_settings.example.py
fence/resources/user/user_session.py
fence/settings.py
tests/session/test_session.py
tests/test_settings.py
tests/utils/__init__.py

fix(time): use time instead of datetime for expiration

---

fence/blueprints/login/__init__.py
tests/login/test_default_login.py

fix URLs in default `/login` endpoint; should not be using `urljoin`

fix(default-login): fix URL joining

---

fence/models.py
requirements.txt
tests/test_datamodel.py

depends on https://github.com/uc-cdis/userdatamodel/pull/33

fix(cascade): fix delete cascade

---

fence/__init__.py
fence/blueprints/login/__init__.py
fence/blueprints/storage_creds.py
run.py

r @rudyardrichter @philloooo 
enable both '/' and '' in the endpoint

fix(slash): strict slash = false

---

fence/__init__.py
fence/resources/aws/boto_manager.py
requirements.txt

- return 401 for jwt error
- fix logger for botomanager

Fix/logger - fix boto logger and auth error

---

bin/fence-create

local_settings is not installed as a module under fence in prod

fix(fence-create): import settings

---

fence/blueprints/storage_creds/__init__.py
fence/blueprints/storage_creds/api.py
fence/local_settings.example.py
fence/settings.py

Add all TTL settings into local_setting
r @rudyardrichter @philloooo

feat(expire): centralize all expiration time

---

requirements.txt

bump for https://github.com/uc-cdis/userdatamodel/pull/36

chore(usermd): bump usermd for fix

---

Dockerfile
fence/settings.py

- enable reqtimeout for slowloris vulnerability
- turn on secure for cookie
partially solve https://github.com/uc-cdis/cloud-automation/issues/219

feat(security): enable reqtimeout, secure cookie

---

fence/blueprints/data.py
tests/conftest.py

coupled with 
https://github.com/uc-cdis/indexd/pull/109

feat(acl): use index doc.acl

---

fence/blueprints/login/fence_login.py

pop requires a default, this is breaking in prod

fix(login): fix pop

---

README.md
fence/blueprints/oauth2.py
fence/blueprints/well_known.py
fence/jwt/token.py
fence/local_settings.example.py
tests/oidc/discovery/test_configuration.py
tests/test_settings.py

feat(oidc-config): add endpoint returning OIDC configuration 

---

fence/blueprints/data.py

allow the bucket configuration specify bucket name as regex

feat(bucket): support regex

---

README.md
fence/blueprints/oauth2.py
fence/local_settings.example.py
tests/multi_tenant/conftest.py
tests/oidc/core/authorization/test_prompt.py

- remove redirect config
- update readme for an outdated instruction

feat(login): remove redirect config

---

Dockerfile

Resolves uc-cdis/cloud-automation#315

fix(log): log to access.log

---

fence/scripting/fence_create.py
fence/sync/sync_users.py
tests/dbgap_sync/conftest.py
tests/dbgap_sync/data/csv/authentication_file_phs000178.txt
tests/dbgap_sync/test_user_sync.py

feat(sync): add consent code

---

fence/sync/sync_users.py

the new sync process didn't check admin field in yaml

fix(sync): read admin field

---

fence/sync/sync_users.py

log the file name so that we know what files we grabbed from dbgap

chore(dbgap): log parsed dbgap file

---

fence/jwt/token.py

Adding uppercase letters, periods, some brief language change. I don't feel super strong about any of the changes, and willing to change more.

Edit displayed scope language

---

fence/auth.py
tests/test_logout.py

- error is not displayed if someone tries to logout when they are not logged in. WIP.

PXD-641 Logout error handling

---

fence/blueprints/data.py
fence/local_settings.example.py
fence/resources/aws/boto_manager.py
requirements.txt
tests/conftest.py
tests/test_data.py
tests/test_settings.py

Add across accounts presigned url
- Change structure of S3_BUCKETS to have type of bucket
- if internal -> refer to key AWS_CREDENTIALS
- if external -> refer to key in ASSUME_ROLES, then get reference to AWS_CREDENTIALS
r @zflamig @philloooo @rudyardrichter 
related prs:
https://github.com/uc-cdis/cdis-python-utils/pull/29

PXD-278: feat(assume-role): cross accounts assuming role

---

bin/fence-create
fence/blueprints/google.py
fence/resources/google/access_utils.py
fence/resources/google/utils.py
fence/resources/google/validity.py
fence/scripting/google_monitor.py
fence/settings.py
tests/conftest.py
tests/google/conftest.py
tests/google/test_google_monitor.py
tests/test_data.py

PXD-1029 Feat/validation scripts

---

.travis.yml

fix env var in travis file to run wool

fix(wool): fix travis file

---

Dockerfile
fence/__init__.py
fence/blueprints/misc.py
fence/version_data.py
tests/test_misc.py

add _status and _version endpoint

feat(misc): add misc blueprint

---

bin/fence-create
fence/__init__.py
fence/local_settings.example.py
fence/resources/google/access_utils.py
fence/resources/google/utils.py
fence/resources/google/validity.py
fence/scripting/fence_create.py
fence/scripting/google_monitor.py
fence/utils.py
tests/google/test_access_utils.py
tests/google/test_google_monitor.py
tests/oidc/core/authorization/test_prompt.py
tests/test_settings.py

FN364 ⁃ email users/client when a user-registered service account gets kicked off for being invalid

PXD-1371 Feat/email

---

fence/sync/sync_users.py

Revert "fix(arborist): don't create root resource"

---

fence/rbac/client.py
fence/sync/sync_users.py

- use fixed update endpoint for resource if the resource already exists
- remove delete requests
- mute expected failure

fix(arborist): upsert resources

---

pull_request_template.md

add a pull request template that will automatically populate when a dev make a new PR. The developer will need to fill with appropriate content in each PR. 
We will automate the release generation to compile PR descriptions to release notes.

chore(template): add pull request template

---

pull_request_template.md

Mention the DEV guidelines in the PR template
- added a reminder to follow the guidelines

feat(pr_template): add dev guidelines

---

requirements.txt

fix(flask): bump flask version

---

fence/scripting/google_monitor.py

- only send emails to owners on current project
- reinitialize email variables in each loop

reinitialize email variables each time we validate a project

---

bin/google-user-sa-validation.sh

- use double quote for google user SA validation status json

chore(job): use double quotes

---

fence/resources/google/access_utils.py

- Log user without access to a project.

log users without access to projects

---

fence/blueprints/google.py

- Report error that no project id was included in request.

PXD-2211 Report No Project Name Error Correctly

---

fence/sync/sync_users.py

Raise exception if sync file is empty.

fix(no-sync-file): raise exception if file empty

---

fence/blueprints/google.py
fence/resources/google/validity.py
requirements.txt
tests/google/test_access_utils.py

Update fence to work with new Cirrus errors and new cirrus version
- fixed bug where cirrus library would not retry some Google API calls 
- update cirrus

chore(cirrus): update to new error structure

---

requirements.txt

- don't retry for unauthorized requests to google
- cirrus 0.2.0 -> 0.2.1

chore(dep): bump cirrus for better error handle

---

fence/auth.py
fence/blueprints/login/fence_login.py
fence/errors.py
fence/restful.py
requirements.txt

feat(awg-login): add redirection on failed login back to login page

---

fence/config-default.yaml

fix(config-default): fence indexd username

---

openapis/swagger.yaml

docs(google): clarification about response from endpoint
- update docs with some clarifications about the response for GET /google/service_accounts

docs(google): clarification about response from endpoint

---

fence/resources/google/access_utils.py
requirements.txt
tests/google/test_service_accounts.py

- better error handling for google group member addition
- update cirrus to 0.2.4

fix(google-err-handling): update to handle conflicts better

---

fence/resources/aws/boto_manager.py
fence/resources/google/access_utils.py
fence/resources/google/utils.py
fence/resources/google/validity.py

- Case sensitivity with linked Google accounts
- Improve google account validity checking logging

fix(caps): Fix check on linked google accounts

---

fence/resources/google/validity.py

- Improve google service account registration logging

chore(log): log actual invalid user

---

requirements.txt

fix(reqs): pin requests_oauthlib

---

bin/fence-create

Set default log level to INFO; verbose includes DEBUG

fix(logging): only disable debug by default

---

README.md
bin/fence-create
fence/scripting/fence_create.py

* Allow multiple URLs for both client-create and client-modify
* Fixed bug in client-modify that modified old column

PXD-2119: fix(cli-urls): fix --urls options

---

fence/resources/google/access_utils.py

- more debug logs for google SA validation

chore(logging): more debug logs for google SA validation

---

requirements.txt

chore(dep): bump cirrus

---

Dockerfile
deployment/fence.conf

configure Apache to produce json logs
* configure Apache to produce json logs

fix(apache.conf): setup json logs

---

fence/blueprints/data/indexd.py
fence/blueprints/login/google.py

Add a log statement when generating presigned URLs for data upload.

fix(upload-log): add log for upload url

---

fence/sync/sync_users.py

fix issue https://ctds-planx.atlassian.net/browse/PXP-2417
- do not silently fail for usersync arborist sync failure
- do not attempt to sync to arborist when rbac/resources are not specified

chore(usersync): skip arborist when unspecified

---

fence/blueprints/data/indexd.py

Configurable bucket regions for AWS to avoid GetBucketLocation call

feat(region): Add option to specify bucket region

---

requirements.txt

- Use the latest cirrus release

chore(bump-cirrus)

---

README.md
fence/resources/google/utils.py
requirements.txt
setup.py

- Service accounts now have unique names per namespace by passing through prefix used for Google groups

feat(google-sa): use prefix to namespace google service accounts

---

fence/scripting/fence_create.py
requirements.txt
setup.py

Use PyYaml safe_load() instead of load()
Upgrade PyYaml to 5.1

[PXP-2658] Upgrade PyYAML to 5.1 and use safe_load()

---

fence/blueprints/link.py
fence/blueprints/storage_creds/api.py
fence/blueprints/well_known.py
fence/config-default.yaml
fence/jwt/token.py
fence/models.py
fence/resources/user/user_session.py
fence/utils.py
tests/rfc6749/test_oauth2.py
tests/test-fence-config.yaml
tests/utils/__init__.py

- Allowed scopes for user/client/session now in configuration instead of hard-coded

feat(scopes): move allowed scopes to config

---

fence/blueprints/data/blueprint.py
fence/blueprints/data/indexd.py

Fix small bug of multipart upload endpoint. The bug makes a false alarm on the last step of multipart completion.

fix(multipart_upload): return response

---

requirements.txt
setup.py

bump userdatamodel

---

tests/rfc6749/test_oauth2.py

Add an unittest for the case users provide wrong code for the /authorize endpoint

feat(unittest): add an unittest for incorrect scope

---

fence/blueprints/login/fence_login.py

- fix federated fence login endpoint jwt validation

fix(login): use the right function

---

fence/blueprints/data/blueprint.py
fence/blueprints/data/multipart_upload.py

Fix typos in exception handler

fix(typos): fix typos

---

fence/blueprints/login/__init__.py
fence/blueprints/oauth2.py
openapis/swagger.yaml

chore(oauth2): allow specifying idp

---

.travis.yml
README.md
dev-requirements.txt

chore(travis): add coveralls

---

Dockerfile
deployment/uwsgi/uwsgi.ini
fence/sync/sync_users.py

install mcrypt in Docker image

fix(mcrypt): in new docker base image

---

fence/blueprints/login/fence_login.py
fence/resources/openid/google_oauth2.py
fence/resources/openid/microsoft_oauth2.py
fence/resources/openid/orcid_oauth2.py

- specify upstream idp to require user re-auth. caveat is some IdPs wouldn't support it

chore(logout): require re-auth

---

fence/__init__.py
fence/blueprints/login/fence_login.py
fence/blueprints/login/redirect.py
fence/resources/openid/google_oauth2.py
fence/resources/openid/microsoft_oauth2.py
fence/resources/openid/orcid_oauth2.py

Run the formatter since some unformatted code was merged.

fix/black: re-apply formatter

---

fence/blueprints/privacy.py
tests/privacy-policy/conftest.py
tests/privacy-policy/test_privacy_policy.py

- Fix loading privacy policy file in python3
- Fix caching

fix/privacy-policy: update for python3

---

fence/sync/sync_users.py

- correctly get resource mapping in user sync

fix(usersync)

---

docs/google_architecture.md
fence/config.py

add google organization whitelist to force_default_if_none list in config.py

catch empty whitelist

---

fence/oidc/grants/implicit_grant.py
fence/oidc/grants/oidc_code_grant.py

pass nonce to generate_token in implicit grant flow and include in redirect uri
include nonce in id token in auth code flow token response

fix(nonce): pass nonce to generate_token

---

fence/resources/google/utils.py

- don't assume a token exists when checking for a user's proxy group

fix(google): don't assume token exists

---

fence/blueprints/data/indexd.py
fence/jwt/token.py
tests/data/test_data.py

- rely on db for signed url authz checks, don't rely on incomplete token information
- truncate user access in token instead of completely removing

feat(signed-urls): don't rely on access in token, hit db

---

fence/__init__.py
fence/config-default.yaml

- Configuration to disable automatic database migration

feat(db-migration): allow config to disable auto migration

---

bin/fence-create
fence/scripting/fence_create.py

- new fence-create command for migrating the database
- new cloud automation job for database migration https://github.com/uc-cdis/cloud-automation/pull/977

feat(fence-create): new migrate command to migrate the database

---

fence/sync/sync_users.py

- added logging for when a dbGaP telemetry file is empty or an invalid file path

chore(sync): more logs for empty/invalid dbgap telemetry files

---

bin/fence-create
fence/scripting/fence_create.py

- new fence-create command `google-list-authz-groups` which lists Google groups/buckets and authorization in Fence

feat(fence-create): new command to list Google authorization information

---

fence/resources/user/__init__.py

- add arborist resource mapping to userinfo endpoint

feat(userinfo): add arborist auth mapping to the userinfo endpoint

---

fence/blueprints/login/__init__.py
fence/config-default.yaml

- Fix LOGIN_OPTIONS/ENABLED_IDENTITY_PROVIDERS fence-config backwards compatibility

fix(login-options): fix backwards compatible config

---

fence/sync/sync_users.py
tests/dbgap_sync/test_user_sync.py

- dbgap sync provides read and read-storage to dbgap studies

feat(dbgap): provide read and read-storage access

---

Dockerfile
fence/blueprints/login/__init__.py
fence/config-default.yaml

- Fix DEFAULT_LOGIN_IDP backwards compatibility
- Use python 3 base dockerfile v1.1.0 to disable uwsgi cheaper mode

fix(default-idp)

---

fence/config-default.yaml

improvements: 
Added config to allow additional type of GCP SA

add gcp-sa-cloudscheduler

---

fence/sync/sync_users.py

tiny usersync things
- improve some log messages: fix package name, clarify error about whitelist filename pattern match

chore(logs): improve log msgs and docstring (for usersync)

---

requirements.txt
setup.py

- gen3authz updated to at least 0.4.0 for security updates

chore(deps): update gen3authz for security bump of external libs

---

fence/__init__.py
fence/blueprints/login/__init__.py
fence/blueprints/login/cognito.py
fence/config-default.yaml
fence/resources/openid/cognito_oauth2.py
fence/resources/openid/idp_oauth2.py
requirements.txt

userdatamodel PR: https://github.com/uc-cdis/userdatamodel/pull/71
- Add Cognito as Fence IdP
- Bump userdatamodel to 2.3.2
- To use the new Cognito integration, apply in fence config the changes made to config-default.yaml. Otherwise no action required.

PXP-5613 Feat/cognito

---

docs/base_user.yaml
docs/user.yaml_guide.md
fence/blueprints/data/indexd.py

Add user.yaml guide

---

docs/user.yaml_guide.md
tests/google/test_service_accounts.py

- Add program/project info to user.yaml guide
- Fix "assert 60 <= 59" error in flaky unit tests

add program/project info to user.yaml guide

---

fence/oidc/grants/oidc_code_grant.py
fence/resources/openid/ras_oauth2.py

(fix) RAS perefer UserID

---

.pre-commit-config.yaml
README.md
docs/db_diagram/README.md
docs/user.yaml_guide.md
fence/blueprints/data/multipart_upload.py
fence/config-default.yaml
fence/templates/oauthorize.html
tests/jwt/conftest.py
tests/jwt/test_oversized_jwt.py
tests/scripting/test_fence-create.py
tests/test-fence-config.yaml

chore(hooks): no trailing whitespace

---

fence/resources/user/__init__.py

New behavior at userinfo endpoint: If you hit it with a...
- **Curl request with no headers:** Unauthorized: Please login
- **Curl request with access token header:** Normal userinfo response
- **Browser request with only access token cookie:** Unauthorized: Please login (this is intentional--Fence session management discards the access token if no valid session token is found)
- **Browser request with only session token cookie:** Normal userinfo response, but will not include claims which require checks on access token, e.g. ga4gh_passport_v1
- **Browser request with session and access token cookies:** Normal userinfo response (of course, if the access token is there but doesn't have the right claims/scopes then the corresponding userinfo claims will still be missing)
- In the userinfo …

fix(userinfo): Get access tkn from sessn cookie OR Bearer header

---

fence/config-default.yaml

default config RAS  minor fix

---

fence/blueprints/google.py

Change service account limit error message.

chore: Change service account limit error message.

---

fence/blueprints/google.py

- Service account limit exceeded response from html to json

Fix: change service account response from html to json response

---

fence/blueprints/google.py

- service account project limit error returns acceptable error schema.

fix(service-account): Change response schema

---

fence/blueprints/login/base.py

- Deny redirects to default client redirect_uri instead of given redirect_uri.

Fix(RAS): Deny redirects to default client redirect_uri

---

Dockerfile

Adopting a new parent image to deliver improvement related to Nginx logging.
- Inline Nginx access logs on stdout.

chore(fence): New parent image pybase3-1.4.2

---

openapis/swagger.yaml

- add idp to userinfo response docs

docs(openapi): add idp to userinfo response docs

---

.secrets.baseline
openapis/swagger.yaml
tests/link/test_link.py
tests/test-fence-config.yaml

- Add _status and _version endpoints to Swagger doc

Add _status and _version endpoints to Swagger doc

---

fence/blueprints/login/ras.py

- Fix parsing for redirect url in RAS

Fix Parse URL for RAS

---

docs/user.yaml_guide.md

- Documentation about public data

Documentation about public data

---

.secrets.baseline
fence/__init__.py
fence/config-default.yaml
tests/data/test_data.py
tests/test-fence-config.yaml

Introducing new ENABLE_PROMETHEUS_METRICS config to allow operators to enable/disable metrics
- Introducing new ENABLE_PROMETHEUS_METRICS config to allow operators to enable/disable metrics

chore(observability): Feature flag for Prometheus metrics

---

fence/blueprints/login/__init__.py

- Patch the 'get_all_shib_idps' function to handle bad input from the InCommon discovery endpoint

Patch 'get_all_shib_idps' to handling bad input

---

pyproject.toml

Update pyproject version to 5.0.0

chore(tag): update pyproject version to 5.0.0

---

Dockerfile

- update base image to latest version

Update Dockerfile to update base image

---

fence/blueprints/login/fence_login.py

Jira Ticket: n/a :fire:
- patch to accept old style tokens from fence idp only, since fenceshib cannot be updated to issue new style tokens

fix(fence-idp-jwt-val): Patch to expect old style tokens

---

fence/resources/openid/ras_oauth2.py

Jira Ticket: n/a
Log txn claim from RAS access token on RAS login

chore(log-txn): Log txn from RAS access token

---

pyproject.toml

Update pyproject.toml for new release

---

openapis/swagger.yaml

- Update "/delete" endpoint documentation

Update /delete endpoint documentation

---

Dockerfile
pyproject.toml

- update to latest python base image

feat(image): update to latest base image

---

fence/jwt/token.py
fence/oidc/jwt_generator.py
poetry.lock

- remove deprecated project access from cookies (making them smaller)

feat(cookies): remove deprecated project access from cookies

---

docs/azure_devops_pipeline.md

* Update image links in example `Azure DevOps` pipeline and documentation

update ado pipeline doc links

---

fence/__init__.py
fence/blueprints/login/__init__.py

see [comment](https://github.com/uc-cdis/fence/pull/977#discussion_r750472788) in #977

Remove app param from 'make_login_blueprint()'

---

.secrets.baseline
fence/__init__.py
fence/blueprints/data/blueprint.py
fence/blueprints/data/indexd.py
fence/blueprints/ga4gh.py
fence/blueprints/login/base.py
fence/blueprints/login/ras.py
fence/config-default.yaml
fence/jwt/validate.py
fence/models.py
fence/resources/ga4gh/passports.py
fence/resources/openid/ras_oauth2.py
fence/sync/passport_sync/ras_sync.py
fence/sync/sync_users.py
tests/dbgap_sync/conftest.py
tests/dbgap_sync/test_user_sync.py
tests/ga4gh/test_ga4gh.py
tests/login/test_microsoft_login.py
tests/ras/test_ras.py
tests/test-fence-config.yaml

Jira Ticket: [PXP-8682](https://ctds-planx.atlassian.net/browse/PXP-8682)
- Visa validation and authz sync for POST /data/download/{guid} endpoint
- Requires a database migration to create `iss_sub_pair_to_user` table

(PXP-8682): Add visa validation and sync for data download

---

fence/resources/ga4gh/passports.py
fence/sync/sync_users.py

- Prefix policies created by DRS endpoint so that they don't conflict with usersync policies
- Recreate existing Arborist policies in usersync so that they aren't overwritten

Prefix DRS policies

---

deployment/uwsgi/uwsgi.ini

Increase uWSGI timeouts to 60s.

Increase uWSGI timeouts to 60s.

---

Dockerfile

Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)

Add comments to Dockerfile

---

.secrets.baseline
fence/__init__.py
fence/models.py
fence/resources/ga4gh/passports.py
tests/conftest.py

Jira Ticket: [PXP-8994](https://ctds-planx.atlassian.net/browse/PXP-8994)
Populate `iss_sub_pair_to_user` table using `User` table's `id_from_idp` column. Population of `User` table's `id_from_idp` column began with the `2021.12` [release](https://github.com/uc-cdis/fence/compare/2021.11...2021.12), which included [this related PR](https://github.com/uc-cdis/fence/pull/975). 
- Populate `iss_sub_pair_to_user` table using `User` table's `id_from_idp` column

(PXP-8994): Populate mapping table for existing users

---

.secrets.baseline
fence/blueprints/login/ras.py
fence/config-default.yaml
fence/models.py
fence/resources/ga4gh/passports.py
tests/conftest.py
tests/test-fence-config.yaml
tests/test_drs.py

https://ctds-planx.atlassian.net/browse/PXP-8838
- Passport cache for substantially increasing speed of subsequent parsing of the same, valid passport

feat(passport): add cache [PXP-8838]

---

fence/blueprints/admin.py
fence/blueprints/storage_creds/api.py

Jira Ticket: [PXP-4235](https://ctds-planx.atlassian.net/browse/PXP-4235) (not exactly, but i think this is better?)
- Add all the user's scopes to API keys

PXP-4235 Add all the user's scopes to API keys

---

fence/resources/openid/idp_oauth2.py

Jira Ticket: [PXP-9500](https://ctds-planx.atlassian.net/browse/PXP-9500)
- Fix generic OIDC: `get_user_id` returns the correct user ID field

PXP-9500 Fix generic OIDC: return the correct user_id field

---

fence/blueprints/login/__init__.py

- InCommon: do not configure duplicate Shibboleth IDPs

InCommon: no duplicate IDPs

---

poetry.lock
pyproject.toml

Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)

Update tom file for 6.0.1 release

---

pyproject.toml

Semantic version release 6.1.0

Sem ver release

---

fence/models.py
fence/scripting/fence_create.py
tests/scripting/test_fence-create.py

Fix for https://github.com/uc-cdis/fence/pull/1057

Fix OIDC client expires_at timestamp

---

fence/resources/user/user_session.py

- ensure secure cookies are set based on configuration

feat(cookies): ensure setting secure on cookies

---

fence/sync/sync_users.py

- Use libraries functionality for automatically adding ssh keys

fix(ssh): use libraries functionality for automatically adding ssh keys

---

README.md
fence/sync/sync_users.py

Jira Ticket: [PXP-10910](https://ctds-planx.atlassian.net/browse/PXP-10910)
see fixed integration test in https://github.com/uc-cdis/gen3-qa/pull/944
- Fix access for rotated client credentials
[PXP-10910]: https://ctds-planx.atlassian.net/browse/PXP-10910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-10910 Fix access for rotated client credentials

---

.github/labeler.yml
.github/workflows/labeler.yml

Label PRs to run only relevant tests

---

Dockerfile

Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- Remove libmhash2 dependency

Remove libmhash2 dependency

---

.gitignore
.secrets.baseline
fence/resources/google/utils.py
tests/google/test_access_utils.py
tests/google/test_utils.py

- Adds backoff for the give_service_account_billing_access calls

feat(backoff): Add backoff to give_service_account_billing_access

---

fence/resources/google/access_utils.py
fence/sync/sync_users.py
tests/google/test_access_utils.py

- Fixes issue where get/add/remove members for google groups weren't working.

Use access_utils google methods correctly

---

fence/resources/google/access_utils.py
fence/sync/sync_users.py
tests/dbgap_sync/test_user_sync.py

- Fix usersync  issue where arborist would not receive updates when Google update errors occur.

Catch google errors and raise after usersync finishes

---

poetry.lock
pyproject.toml

- paramiko, for security reasons

chore(deps): upgrade paramiko PPS-707

---

docs/base_user.yaml

- Update base user.yaml in documentation to pass validation

Update base user.yaml to pass validation

---

fence/sync/sync_users.py
tests/dbgap_sync/test_user_sync.py

- Retries failures when downloading authorization files through SFTP.

 backoff.exception for sftp connection

---

poetry.lock
pyproject.toml

Update version in toml

---

docs/additional_documentation/setup.md

- Update documentation link in setup.md

Update documentation link in setup.md

---

fence/blueprints/admin.py

Link to JIRA ticket if there is one:  https://ctds-planx.atlassian.net/browse/VADC-1548
- deprecation notices for future breaking changes where we'll remove a number of legacy endpoints

Feat: deprecate legacy unused /admin/ endpoints

---

Dockerfile
tests/ci_commands_script.sh

- Fix the `_version` endpoint not to return empty values
- Add the database migrations directory to the unit test coverage report

Fix version endpoint

---

Dockerfile

Updated to use Quay.io instead of ECR

switching back to quay.

---

poetry.lock
pyproject.toml

PPS-1928 bump jinja2

---

fence/config-default.yaml
fence/config.py
fence/local_settings.example.py
tests/test-fence-config.yaml

- Clarify what the `MAX_ACCESS_TOKEN_TTL` setting is for in the configuration comments

Clarify what the MAX_ACCESS_TOKEN_TTL setting is

---

fence/blueprints/data/indexd.py

- When a bucket is missing from the `S3_BUCKET` configuration, print an info log instead of a debug log to facilitate understanding issues in production

Info log instead of debug log for missing bucket

---

openapis/swagger.yaml

- Updates openapi docs to include GA4GH endpoint for data access with passports.

Adds GA4GH post endpoint to swagger docs

---

.github/workflows/integration_tests.yaml

Link to JIRA ticket if there is one: [GQE-470](https://ctds-planx.atlassian.net/browse/GQE-470)
[GQE-470]: https://ctds-planx.atlassian.net/browse/GQE-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Switch Fence Service to new HELM based CI Pipeline
